
export type Article = {
  id: string;
  title: string;
  excerpt: string;
  imageUrl: string;
  imageHint: string;
  category: string;
  author: string;
  date: string;
};

export const beautyArticles: Article[] = [
    {
        id: 'glass-skin-routine',
        title: 'The Ultimate Guide to Achieving Glass Skin',
        excerpt: 'Learn the step-by-step Korean skincare routine to get that coveted luminous, poreless, and translucent complexion.',
        imageUrl: 'https://images.unsplash.com/photo-1590152994408-e43543534125?q=80&w=2187&auto=format&fit=crop',
        imageHint: 'skincare products',
        category: 'Skincare',
        author: 'Serena Glass',
        date: '2024-06-10',
    },
    {
        id: 'bold-lip-tutorial',
        title: 'How to Master the Perfect Bold Lip',
        excerpt: 'A step-by-step tutorial on how to prep, line, and apply lipstick for a flawless, long-lasting bold lip that won\'t smudge.',
        imageUrl: 'https://images.unsplash.com/photo-1671288239289-f01976a87c43?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHx3b21hbiUyMGxpcHN0aWNrfGVufDB8fHx8MTc2MjYwMzAwNHww&ixlib=rb-4.1.0&q=80&w=1080',
        imageHint: 'bold lipstick',
        category: 'Makeup',
        author: 'Ruby Red',
        date: '2024-06-08',
    },
    {
        id: 'retinol-for-beginners',
        title: 'Retinol for Beginners: A Complete Guide',
        excerpt: 'Everything you need to know before adding retinol to your skincare routine, from choosing the right strength to avoiding irritation.',
        imageUrl: 'https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxza2luY2FyZSUyMHByb2R1Y3RzfGVufDB8fHx8MTc2MjUzMTM0OXww&ixlib=rb-4.1.0&q=80&w=1080',
        imageHint: 'serum bottle',
        category: 'Skincare',
        author: 'Dr. Erin Derm',
        date: '2024-06-05',
    },
    {
        id: 'graphic-eyeliner-looks',
        title: 'Unleash Your Inner Artist: 5 Graphic Eyeliner Looks to Try',
        excerpt: 'Move beyond the classic wing with these creative and eye-catching graphic eyeliner styles that are surprisingly easy to recreate.',
        imageUrl: 'https://images.unsplash.com/photo-1625094640367-05f84293fe42?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxleWVzaGFkb3clMjBwYWxldHRlfGVufDB8fHx8MTc2MjU1NjI0NHww&ixlib=rb-4.1.0&q=80&w=1080',
        imageHint: 'graphic eyeliner',
        category: 'Tutorials',
        author: 'Lina Art',
        date: '2024-06-02',
    },
    {
        id: 'sunscreen-every-day',
        title: 'Why You Need to Wear Sunscreen Every Single Day',
        excerpt: 'A deep dive into the importance of daily sun protection for preventing premature aging and reducing skin cancer risk.',
        imageUrl: 'https://images.unsplash.com/photo-1580554763125-89498da13f9c?q=80&w=2070&auto=format&fit=crop',
        imageHint: 'sunscreen application',
        category: 'Skincare',
        author: 'Sunny Shield',
        date: '2024-05-30',
    },
    {
        id: 'no-makeup-makeup',
        title: 'The "No-Makeup" Makeup Look in 5 Easy Steps',
        excerpt: 'Achieve a fresh, flawless, and natural-looking face with this quick and simple "no-makeup" makeup tutorial.',
        imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=2080&auto=format&fit=crop',
        imageHint: 'natural makeup',
        category: 'Tutorials',
        author: 'Mia Natural',
        date: '2024-05-28',
    },
    {
        id: 'hair-slugging-trend',
        title: 'Hair Slugging: The Viral Trend for Softer, Shinier Hair',
        excerpt: 'Could coating your hair in oil overnight be the secret to luscious locks? We investigate the "hair slugging" trend.',
        imageUrl: 'https://images.unsplash.com/photo-1599388825375-068393666336?q=80&w=2187&auto=format&fit=crop',
        imageHint: 'healthy hair',
        category: 'Haircare',
        author: 'Holly Locks',
        date: '2024-05-26',
    },
];

export const yogaArticles: Article[] = [
  {
    id: 'deepen-your-practice',
    title: '5 Ways to Deepen Your Yoga Practice',
    excerpt: 'Move beyond the physical postures and explore the philosophical and spiritual dimensions of yoga to enrich your life on and off the mat.',
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=2120&auto=format&fit=crop',
    imageHint: 'woman yoga pose',
    category: 'Mindfulness',
    author: 'Elena Sage',
    date: '2024-05-20',
  },
  {
    id: 'morning-yoga-routine',
    title: 'The Perfect 15-Minute Morning Yoga Routine',
    excerpt: 'Start your day with energy and clarity. This short and effective routine is designed to awaken your body and focus your mind.',
    imageUrl: 'https://images.unsplash.com/photo-1591291621220-9092a7cc3f10?q=80&w=2187&auto=format&fit=crop',
    imageHint: 'yoga morning',
    category: 'Practice',
    author: 'Leo Ascent',
    date: '2024-05-18',
  },
  {
    id: 'benefits-of-meditation',
    title: 'Unlocking Stillness: The Core Benefits of Meditation',
    excerpt: 'Discover how a consistent meditation practice can reduce stress, improve concentration, and foster a deeper sense of well-being.',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-4e652a97b975?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'meditation outdoors',
    category: 'Mindfulness',
    author: 'Serena Peace',
    date: '2024-05-15',
  },
    {
    id: 'beginner-poses',
    title: 'Essential Yoga Poses for Absolute Beginners',
    excerpt: 'New to yoga? These foundational poses will help you build strength, increase flexibility, and start your practice with confidence.',
    imageUrl: 'https://images.unsplash.com/photo-1575052814086-c389226cd8b2?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'beginner yoga',
    category: 'Practice',
    author: 'Alex Foundation',
    date: '2024-05-12',
  },
  {
    id: 'yoga-for-stress-relief',
    title: 'Flow and Let Go: Yoga for Stress Relief',
    excerpt: 'Learn how specific yoga sequences and breathing techniques can calm your nervous system and melt away the stresses of daily life.',
    imageUrl: 'https://images.unsplash.com/photo-1607748862156-71a68aa736a6?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'stress relief yoga',
    category: 'Wellness',
    author: 'Hannah Bloom',
    date: '2024-05-10',
  },
  {
    id: 'mindful-eating',
    title: 'Nourish Your Body: An Introduction to Mindful Eating',
    excerpt: 'Transform your relationship with food by bringing the principles of mindfulness to your meals. Savor every bite and listen to your body.',
    imageUrl: 'https://images.unsplash.com/photo-1542844378-4795c453b754?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'healthy food',
    category: 'Wellness',
    author: 'Gia Harvest',
    date: '2024-05-08',
  },
  {
    id: 'history-of-yoga',
    title: 'From Ancient Roots: A Brief History of Yoga',
    excerpt: 'Explore the fascinating origins of yoga, from its ancient beginnings in India to its evolution into the global phenomenon it is today.',
    imageUrl: 'https://images.unsplash.com/photo-1599905291214-d57a27625145?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'ancient temple',
    category: 'Philosophy',
    author: 'Rohan Vedas',
    date: '2024-05-05',
  },
];


export const newsArticles: Article[] = [
  {
    id: 'summer-beauty-trends',
    title: 'Top 5 Beauty Trends to Try This Summer',
    excerpt: 'From glossy lips to bold eyeshadows, discover the hottest beauty trends that are taking over this summer.',
    imageUrl: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?q=80&w=2080&auto=format&fit=crop',
    imageHint: 'summer beauty',
    category: 'Trends',
    author: 'Julia Styles',
    date: '2024-06-01',
  },
  {
    id: 'skincare-mistakes',
    title: 'Are You Making These Common Skincare Mistakes?',
    excerpt: 'A leading dermatologist breaks down the most common mistakes people make in their skincare routines and how to fix them for healthier skin.',
    imageUrl: 'https://images.unsplash.com/photo-1552046122-03184de85e08?q=80&w=2187&auto=format&fit=crop',
    imageHint: 'skincare routine',
    category: 'Skincare',
    author: 'Dr. Anya Sharma',
    date: '2024-05-28',
  },
  {
    id: 'celebrity-interview',
    title: 'Exclusive: Celebrity MUA Shares Red Carpet Secrets',
    excerpt: 'We sit down with a world-renowned makeup artist to get the inside scoop on how she preps A-listers for the red carpet.',
    imageUrl: 'https://images.unsplash.com/photo-1616099079201-3837a8951859?q=80&w=2187&auto=format&fit=crop',
    imageHint: 'makeup artist',
    category: 'Interviews',
    author: 'Chloe Reporter',
    date: '2024-05-25',
  },
    {
    id: 'new-product-launch',
    title: 'The Viral Foundation That’s Selling Out Everywhere',
    excerpt: 'A new foundation has taken the internet by storm. We investigate if it lives up to the hype and where you can get your hands on it.',
    imageUrl: 'https://images.unsplash.com/photo-1590152994408-e43543534125?q=80&w=2187&auto=format&fit=crop',
    imageHint: 'foundation product',
    category: 'Products',
    author: 'Ben Filter',
    date: '2024-05-22',
  },
  {
    id: 'diy-face-masks',
    title: 'Natural Glow: 3 DIY Face Masks You Can Make at Home',
    excerpt: 'Get radiant skin with these simple and effective DIY face masks using ingredients you probably already have in your kitchen.',
    imageUrl: 'https://images.unsplash.com/photo-1596524430615-b46475ddff6e?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'DIY facemask',
    category: 'DIY Beauty',
    author: 'Aisha Green',
    date: '2024-05-19',
  },
  {
    id: 'clean-beauty',
    title: 'What Is "Clean Beauty" and Why Does It Matter?',
    excerpt: 'We delve into the world of clean beauty, explaining what the term means, what ingredients to avoid, and how to make more conscious choices.',
    imageUrl: 'https://images.unsplash.com/photo-1562157873-818bc0726f68?q=80&w=1974&auto=format&fit=crop',
    imageHint: 'natural ingredients',
    category: 'Wellness',
    author: 'Terra Bloom',
    date: '2024-05-17',
  },
  {
    id: 'perfect-eyebrow',
    title: 'How to Shape Your Eyebrows Like a Pro',
    excerpt: 'Learn the secrets to achieving the perfect eyebrow shape for your face, from mapping and trimming to filling them in for a natural look.',
    imageUrl: 'https://images.unsplash.com/photo-1589779348943-7195e4321975?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'eyebrow shaping',
    category: 'Tutorials',
    author: 'Archibald Lee',
    date: '2024-05-14',
  },
  {
    id: 'sunscreen-guide',
    title: 'The Ultimate Sunscreen Guide: SPF, UVA, UVB Explained',
    excerpt: 'Sunscreen is the most important step in your skincare routine. Understand the jargon and find the best protection for your skin type.',
    imageUrl: 'https://images.unsplash.com/photo-1580554763125-89498da13f9c?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'sunscreen application',
    category: 'Skincare',
    author: 'Dr. Ray Solaris',
    date: '2024-05-11',
  },
];

export const healthArticles: Article[] = [
  {
    id: 'holistic-health-guide',
    title: 'A Beginner\'s Guide to Holistic Health',
    excerpt: 'Explore the foundations of holistic health, which considers the whole person—body, mind, spirit, and emotions—in the quest for optimal wellness.',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'healthy food bowl',
    category: 'Holistic',
    author: 'Aura Wellness',
    date: '2024-06-03',
  },
  {
    id: 'sleep-hygiene',
    title: 'The Art of Sleep: 8 Tips for Better Rest',
    excerpt: 'Struggling to get a good night\'s sleep? These expert-backed tips on sleep hygiene can help you improve your sleep quality and overall health.',
    imageUrl: 'https://images.unsplash.com/photo-1530530972418-5452683a3233?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'person sleeping',
    category: 'Lifestyle',
    author: 'Dr. Remy Sleepwell',
    date: '2024-06-01',
  },
  {
    id: 'superfoods-2024',
    title: 'Superfoods for 2024: What to Add to Your Diet',
    excerpt: 'From moringa to mushrooms, discover the nutrient-packed superfoods that nutritionists are recommending for a major health boost this year.',
    imageUrl: 'https://images.unsplash.com/photo-1542844378-4795c453b754?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'superfood smoothie',
    category: 'Nutrition',
    author: 'Nina Nutrient',
    date: '2024-05-29',
  },
  {
    id: 'gut-health-importance',
    title: 'Gut Feeling: Why Your Microbiome is Key to Health',
    excerpt: 'The health of your gut impacts everything from your immune system to your mood. Learn how to cultivate a healthy gut microbiome.',
    imageUrl: 'https://images.unsplash.com/photo-1528740096961-3798add19cb7?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'fermented food',
    category: 'Nutrition',
    author: 'Polly Probiotic',
    date: '2024-05-27',
  },
  {
    id: 'digital-detox',
    title: 'How to Do a Digital Detox (and Why You Need One)',
    excerpt: 'Feeling overwhelmed by screens? A digital detox can help you reset, reduce stress, and reconnect with the world around you. Here\'s how to start.',
    imageUrl: 'https://images.unsplash.com/photo-1516245834210-c4c1427873ab?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'nature landscape',
    category: 'Mental Health',
    author: 'Calm Connect',
    date: '2024-05-24',
  },
  {
    id: 'hydration-myths',
    title: 'H2-Oh! Debunking Common Hydration Myths',
    excerpt: 'Are you really drinking enough water? We separate fact from fiction when it comes to hydration and its importance for your body.',
    imageUrl: 'https://images.unsplash.com/photo-1550426296-7a42784a5c7f?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'drinking water',
    category: 'Lifestyle',
    author: 'Aqua Pure',
    date: '2024-05-21',
  },
  {
    id: 'mindful-movement',
    title: 'Beyond the Gym: Finding Joy in Mindful Movement',
    excerpt: 'Exercise doesn\'t have to be a chore. Discover forms of movement that you genuinely enjoy, from dancing to hiking, and make fitness a sustainable habit.',
    imageUrl: 'https://images.unsplash.com/photo-1502224514721-9d3b3478de2b?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'person hiking',
    category: 'Fitness',
    author: 'Motion Matt',
    date: '2024-05-18',
  },
  {
    id: 'herbal-teas',
    title: 'A Guide to Herbal Teas for Relaxation and Health',
    excerpt: 'Chamomile for sleep, peppermint for digestion, ginger for immunity. Explore the wonderful world of herbal teas and their health benefits.',
    imageUrl: 'https://images.unsplash.com/photo-1594751543129-97692d47352b?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'herbal tea',
    category: 'Wellness',
    author: 'Camellia Day',
    date: '2024-05-15',
  },
];

export const growthArticles: Article[] = [
  {
    id: 'mastering-new-skills',
    title: 'The Art of Mastering New Skills in Record Time',
    excerpt: 'Unlock your learning potential with these proven techniques for acquiring new skills faster and more effectively than ever before.',
    imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=2084&auto=format&fit=crop',
    imageHint: 'team working together',
    category: 'Productivity',
    author: 'Leo Peak',
    date: '2024-06-05',
  },
  {
    id: 'financial-freedom',
    title: 'Your Roadmap to Financial Freedom',
    excerpt: 'Take control of your finances with this step-by-step guide to budgeting, investing, and building long-term wealth.',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-169544351720?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'calculating finances',
    category: 'Finance',
    author: 'Penny Wise',
    date: '2024-06-03',
  },
  {
    id: 'building-confidence',
    title: 'How to Build Unshakable Self-Confidence',
    excerpt: 'Confidence is a skill, not a trait. Learn practical strategies to overcome self-doubt and project confidence in any situation.',
    imageUrl: 'https://images.unsplash.com/photo-1583344448000-681e5b7c4a93?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'confident person',
    category: 'Mindset',
    author: 'Valerie Valor',
    date: '2024-06-01',
  },
    {
    id: 'networking-like-a-pro',
    title: 'Networking Like a Pro: Build Meaningful Connections',
    excerpt: 'Move beyond awkward small talk. These tips will help you build a strong professional network based on genuine relationships.',
    imageUrl: 'https://images.unsplash.com/photo-1531538606176-4f92d52ce021?q=80&w=2148&auto=format&fit=crop',
    imageHint: 'people networking',
    category: 'Career',
    author: 'Connie Chan',
    date: '2024-05-30',
  },
  {
    id: 'the-power-of-habits',
    title: 'The Power of Habits: Small Changes, Big Results',
    excerpt: 'Discover how to build good habits and break bad ones. It\'s the small, consistent actions that lead to massive long-term success.',
    imageUrl: 'https://images.unsplash.com/photo-1517842642056-3393d9396122?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'person writing',
    category: 'Productivity',
    author: 'James Clear-ish',
    date: '2024-05-28',
  },
  {
    id: 'overcoming-procrastination',
    title: 'Beat Procrastination for Good: A 5-Step Plan',
    excerpt: 'Stop putting things off and start getting things done. This practical guide will help you understand and overcome the urge to procrastinate.',
    imageUrl: 'https://images.unsplash.com/photo-1542988533-3a3bf6813b1b?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'stressed person',
    category: 'Productivity',
    author: 'Tia Mely',
    date: '2024-05-25',
  },
  {
    id: 'public-speaking-tips',
    title: 'Speak with Confidence: Public Speaking for Beginners',
    excerpt: 'Turn your fear of public speaking into your greatest asset. These tips will help you command a room and deliver a compelling presentation.',
    imageUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?q=80&w=2070&auto=format&fit=crop',
    imageHint: 'public speaking',
    category: 'Career',
    author: 'Orville Orator',
    date: '2024-05-22',
  },
];

