import {
  Twitter,
  Facebook,
  Instagram,
  Linkedin,
  Youtube,
  Github,
  Gitlab,
  Twitch,
  Slack,
  Figma,
  Dribbble,
  Rss,
  MessageCircle,
  Mail,
  Share2,
  ExternalLink,
  Link,
  Code,
  Codepen,
  Codesandbox,
  GitBranch,
  Star,
  Home,
  PlusCircle,
  Coins,
  Store,
  LineChart,
  Newspaper,
  LifeBuoy,
  FileText,
  Wallet,
  Flower,
  Goal,
  Heart,
  HelpCircle,
  HeartPulse,
  TrendingUp,
  Compass,
  PenTool,
  Camera,
  AppWindow,
} from 'lucide-react';

export const socialIcons = [
  { name: 'Twitter', icon: Twitter },
  { name: 'Facebook', icon: Facebook },
  { name: 'Instagram', icon: Instagram },
  { name: 'LinkedIn', icon: Linkedin },
  { name: 'YouTube', icon: Youtube },
  { name: 'GitHub', icon: Github },
  { name: 'GitLab', icon: Gitlab },
  { name: 'Twitch', icon: Twitch },
  { name: 'Slack', icon: Slack },
  { name: 'Figma', icon: Figma },
  { name: 'Dribbble', icon: Dribbble },
  { name: 'RSS', icon: Rss },
  { name: 'Messages', icon: MessageCircle },
  { name: 'Mail', icon: Mail },
  { name: 'Share', icon: Share2 },
  { name: 'External', icon: ExternalLink },
  { name: 'Link', icon: Link },
  { name: 'Code', icon: Code },
  { name: 'Codepen', icon: Codepen },
  { name: 'Sandbox', icon: Codesandbox },
  { name: 'Branch', icon: GitBranch },
  { name: 'Star', icon: Star },
  { name: 'Home', icon: Home },
  { name: 'Coins', icon: Coins },
  { name: 'Shop', icon: Store },
  { name: 'Coin Shop', icon: Store },
  { name: 'Analytics', icon: LineChart },
  { name: 'In-App', icon: AppWindow },
  { name: 'News', icon: Newspaper },
  { name: 'Support', icon: LifeBuoy },
  { name: 'Terms', icon: FileText },
  { name: 'Wallet', icon: Wallet },
  { name: 'Yoga', icon: Flower },
  { name: 'Mission', icon: Goal },
  { name: 'Likes', icon: Heart },
  { name: 'Help', icon: HelpCircle },
  { name: 'Health', icon: HeartPulse },
  { name: 'Growth', icon: TrendingUp },
  { name: 'Explore', icon: Compass },
  { name: 'Creator', icon: PenTool },
  { name: 'Camera', icon: Camera },
];
