import {
  Twitter,
  Facebook,
  Instagram,
  Linkedin,
  Youtube,
  Github,
  Gitlab,
  Twitch,
  Slack,
  Figma,
  Dribbble,
  Behance,
  Rss,
  Reddit,
  MessageCircle,
  Mail,
  Share2,
  ExternalLink,
  Link,
  Code,
  Codepen,
  Codesandbox,
  GitBranch,
  Star,
  Home,
  PlusCircle
} from 'lucide-react';

export const socialIcons = [
  { name: 'Twitter', icon: Twitter },
  { name: 'Facebook', icon: Facebook },
  { name: 'Instagram', icon: Instagram },
  { name: 'LinkedIn', icon: Linkedin },
  { name: 'YouTube', icon: Youtube },
  { name: 'GitHub', icon: Github },
  { name: 'GitLab', icon: Gitlab },
  { name: 'Twitch', icon: Twitch },
  { name: 'Slack', icon: Slack },
  { name: 'Figma', icon: Figma },
  { name: 'Dribbble', icon: Dribbble },
  { name: 'Behance', icon: Behance },
  { name: 'RSS', icon: Rss },
  { name: 'Reddit', icon: Reddit },
  { name: 'MessageCircle', icon: MessageCircle },
  { name: 'Mail', icon: Mail },
  { name: 'Share2', icon: Share2 },
  { name: 'ExternalLink', icon: ExternalLink },
  { name: 'Link', icon: Link },
  { name: 'Code', icon: Code },
  { name: 'Codepen', icon: Codepen },
  { name: 'Codesandbox', icon: Codesandbox },
  { name: 'GitBranch', icon: GitBranch },
  { name: 'Star', icon: Star },
  { name: 'Home', icon: Home },
];
